CREATE TABLE customers (
    customer_id VARCHAR(50),
    customer_zip_code_prefix INT,
    customer_city VARCHAR(100),
    customer_state VARCHAR(10)
);

SELECT * FROM customers;

CREATE TABLE products(
	product_id VARCHAR(50),
	product_catagory_name VARCHAR(100),
	product_weight_g INT,
	product_length_cm INT,
	product_height_cm INT,
	product_width_cm INT
);

SELECT * FROM products;

CREATE TABLE orders(
	order_id VARCHAR(50),
	customer_id VARCHAR(50),
	order_purchase_timestamp TIMESTAMP,
	order_approve_at TIMESTAMP
);

SELECT * FROM orders;

CREATE TABLE order_items(
	order_id VARCHAR(50),
	product_id VARCHAR(50),
	seller_id VARCHAR(50),
	price NUMERIC(10,2),
	shipping_charges NUMERIC(10,2)
);

SELECT * FROM order_items;

CREATE TABLE payments(
	order_id VARCHAR(50),
	payment_sequential INT,
	payment_type VARCHAR(50),
	payment_installments INT,
	payment_value NUMERIC(10,2)
);

SELECT * FROM payments;



-- Imp. Instructions: Write SQL queries using aggregate functions 
-- only (COUNT, SUM, AVG, MIN, MAX, GROUP BY, HAVING). 
-- Each question must be answered using only the specified table.

-- A. Customers
--	 1. Find the total number of customers.
		SELECT COUNT(*) AS total_customers FROM customers;


		
-- 	 2. Count how many distinct customer cities are present.
		SELECT COUNT(DISTINCT customer_city) AS distinct_cities FROM customers;



-- 	 3. Find the number of customers in each state and list the top 10 states by customer count.
		SELECT customer_state , COUNT(*) AS customer_count FROM customers
		GROUP BY customer_state
		ORDER BY customer_count DESC LIMIT 10;


		
--   4. Identify the ZIP code prefix with the highest number of customers.
		SELECT customer_zip_code_prefix , COUNT(*) AS customer_count FROM customers
		GROUP BY customer_zip_code_prefix
		ORDER BY customer_count DESC LIMIT 1;


--   5. Count how many ZIP code prefixes have at least 100 customers
		SELECT customer_zip_code_prefix , COUNT(*) AS total_customer FROM customers
		GROUP BY customer_zip_code_prefix 
		having COUNT(*) >= 100;



-- B. Orders
--	1. Find the total number of orders.
	SELECT COUNT(*) AS total_order FROM orders;

	
--	2. Find how many distinct customers have placed at least one order.
	SELECT COUNT(DISTINCT customer_id) AS distinct_order FROM orders;


--	3. Calculate the number of orders placed in each month.
	SELECT EXTRACT(MONTH FROM order_purchase_timestamp) AS month,
	COUNT(order_id) AS total_orders 
	FROM orders
	GROUP BY EXTRACT(MONTH FROM order_purchase_timestamp)
	ORDER BY month;
	

--	4. Compute the average delivery time for orders that have been delivered.
		SELECT AVG(order_approved_at - order_purchase_timestamp) AS avg_delivery_time
		FROM orders
		WHERE order_approved_at IS NOT NULL;



-- C. Order Items
-- 		1. Find the total number of order item records.
			SELECT COUNT(*) AS total_order FROM order_items;

			
--		2. Calculate the average, minimum, and maximum item price.
			SELECT AVG(price) AS avg_payment_amount ,
			MAX(price) AS max_amount,
			MIN(price) AS min_amount
			FROM order_items;



--		3. Compute the total revenue generated from all order items
			SELECT SUM(price) AS total_revenue FROM order_items;

			
--		4. Find the top 10 orders with the highest number of items.
			SELECT order_id,COUNT(*) AS item_count
			FROM order_items
			GROUP BY order_id
			ORDER BY item_count DESC LIMIT 10;

			
--		5. Calculate total revenue generated by each seller and list the top 10 sellers.
			SELECT seller_id , SUM(price) AS total_revenue 
			FROM order_items
			GROUP BY seller_id
			ORDER BY total_revenue DESC LIMIT 10;


-- D. Payments
--		1. Find the total number of payment records.
			SELECT COUNT(*) AS total_payment_records FROM payments;

			
--		2. Calculate the total payment value collected.
			SELECT SUM(payment_value) AS total_payment_value FROM payments;


--		3. Count how many payments were made using each payment type.
			SELECT payment_type,COUNT(*) AS payment_count FROM payments
			GROUP BY payment_type;


--		4. Calculate the average payment value for each payment type.
			SELECT payment_type , AVG(payment_value) AS avg_payment_value
			FROM payments
			GROUP BY payment_type;


--		5. Identify the maximum number of installments used and count how many orders used it.
			SELECT MAX(payment_installments) AS max_number_of_installments , 
			COUNT(*) AS total_orders FROM payments
			WHERE payment_installments = (SELECT MAX(payment_installments) FROM payments
			);



-- E. Products
--		1. Find the total number of products.
			SELECT COUNT(*) AS total_products FROM products;


--		2. Count the number of products in each product category and list the top 10 categories.
			SELECT product_catagory_name , COUNT(*) AS number_of_products
			FROM products
			GROUP BY product_catagory_name
			ORDER BY number_of_products DESC LIMIT 10;


--		3. Calculate the average product weight.
			SELECT AVG(product_weight_g) AS avg_product_weight FROM products;


--		4. Find the minimum and maximum values of product length, height, and width.
			SELECT
				MAX(product_length_cm) AS max_length,
				MIN(product_length_cm) AS min_length,
				
				MAX(product_height_cm) AS max_height,
				MIN(product_height_cm) AS min_height,
				
				MAX(product_width_cm)  AS max_width,
				MIN(product_width_cm)  AS min_width
				FROM products;
				
				

--		5. Identify product categories that have at least 200 products.
			SELECT product_catagory_name , COUNT(*) AS total_products FROM products
			GROUP BY product_catagory_name
			HAVING COUNT(*) >= 200;




-- Easy Level
--		1. Count the total number of customers in the database.
			SELECT COUNT(*) AS total_customers FROM customers;


			
--		2. Count the number of customers belonging to a specific state.
			SELECT COUNT(*) AS customers_in_state
			FROM customers
			WHERE customer_state = 'SP';



--		3. Find the maximum weight among all products.
			SELECT MAX(product_weight_g) AS max_product_weight FROM products;


--		4. Calculate the average payment value across all payments.
			SELECT AVG(payment_value) AS avg_payment_value FROM payments;


--		5. Count the total number of orders placed.
			SELECT COUNT(*) AS total_orders FROM orders;





-- Moderate Level
-- 		1. Display the number of customers in each state.
			SELECT customer_state , COUNT(*) AS total_customers 
			FROM customers
			GROUP BY customer_state;



--		2. Find the average product weight for each product category.
			SELECT 
			    product_catagory_name,
			    AVG(product_weight_g) AS avg_product_weight
			FROM products
			GROUP BY product_catagory_name;


--		3. Count the number of orders that have not yet been approved.
			SELECT COUNT(*) AS unapproved_orders FROM orders
			WHERE order_approve_at IS NULL;


--		4. Calculate the total payment value collected for each payment type.
			SELECT payment_type , SUM(payment_value) AS total_payment_value FROM payments
			GROUP BY payment_type;


--		5. Find the average shipping charges for each seller.
			SELECT seller_id , AVG(shipping_charges) AS avg_shipping_charges FROM order_items
			GROUP BY seller_id;
			



-- Hard Level
--		1. Identify product categories that have more than a specified number of products.
			SELECT product_catagory_name , COUNT(*) AS product_count 
			FROM products
			GROUP BY product_catagory_name
			HAVING COUNT(*) >= 200;


--		2. Find the top five cities with the highest number of customers.
			SELECT customer_city , COUNT(*) AS top_ones
			FROM customers
			GROUP BY customer_city
			ORDER BY top_ones DESC LIMIT 5;


--		3. Identify sellers whose average product price is higher than the overall average product price.
			SELECT seller_id , AVG(price) AS avg_selling_price 
			FROM order_items
			GROUP BY seller_id
			HAVING AVG(price) > (SELECT AVG(price) FROM order_items);


--		4. Find payment types where the maximum payment value exceeds a given threshold.
			SELECT payment_type , MAX(payment_value) AS max_payment
			FROM payments
			GROUP BY payment_type
			hAVING MAX(payment_value) > 5000;


--		5. Identify orders that have more than one associated payment record.
			SELECT order_id , COUNT(*) AS payment_count
			FROM payments
			GROUP BY order_id
			HAVING COUNT(*) > 1;
